### ISSUE TITLE
ERR_BUFFER_OUT_OF_BOUNDS

### ISSUE THREAD

**Issue by hkjeffchan** [Kononnable/typeorm-model-generator#127]
typeorm-model-generator -h 127.0.0.1 -p 8889 -d testdb -u root -x root --cf camel --ce camel --cp camel
```
Starting creation of model classes.
internal/buffer.js:53
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:53:11)
    at Buffer.readUInt8 (internal/buffer.js:143:5)
    at Packet.type (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/tedious/lib/packet.js:144:26)
    at IncomingMessageStream.processBufferedData (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/tedious/lib/incoming-message-stream.js:76:50)
    at IncomingMessageStream._transform (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/tedious/lib/incoming-message-stream.js:113:12)
    at IncomingMessageStream.Transform._read (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at IncomingMessageStream.Transform._write (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at IncomingMessageStream.Writable.write (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/readable-stream/lib/_stream_writable.js:334:11)
```

**Comment by hkjeffchan** [comment]
Sorry, i am an idiot and missed the engine flag.
