### ISSUE TITLE
Unknown column type: bit

### ISSUE THREAD

**Issue by P0oOOOo0YA** [Kononnable/typeorm-model-generator#128]
This is [MySQL dump](https://www.openthesaurus.de/export/openthesaurus_dump.tar.bz2) of the database I'm trying to get entities from using `typeorm-model-generator`.  and this is `typeorm-model-generator` log

```
typeorm-model-generator@0.2.22
[2:38:59 PM] Starting creation of model classes.
Unknown column type: bit  table name: category column name: is_disabled
Error occured in typeorm-model-generator.
typeorm-model-generator@0.2.22  node@v8.11.2
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
Error
    at Object.LogError (/usr/lib/node_modules/typeorm-model-generator/dist/src/Utils.js:10:21)
    at response.filter.forEach.resp (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:160:39)
    at Array.forEach (<anonymous>)
    at entities.forEach.ent (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:38:22)
    at Array.forEach (<anonymous>)
    at MariaDbDriver.<anonymous> (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:33:22)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unknown column type: bit  table name: language column name: is_disabled
Error occured in typeorm-model-generator.
typeorm-model-generator@0.2.22  node@v8.11.2
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
Error
    at Object.LogError (/usr/lib/node_modules/typeorm-model-generator/dist/src/Utils.js:10:21)
    at response.filter.forEach.resp (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:160:39)
    at Array.forEach (<anonymous>)
    at entities.forEach.ent (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:38:22)
    at Array.forEach (<anonymous>)
    at MariaDbDriver.<anonymous> (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:33:22)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unknown column type: bit  table name: synset column name: is_visible
Error occured in typeorm-model-generator.
typeorm-model-generator@0.2.22  node@v8.11.2
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
Error
    at Object.LogError (/usr/lib/node_modules/typeorm-model-generator/dist/src/Utils.js:10:21)
    at response.filter.forEach.resp (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:160:39)
    at Array.forEach (<anonymous>)
    at entities.forEach.ent (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:38:22)
    at Array.forEach (<anonymous>)
    at MariaDbDriver.<anonymous> (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:33:22)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Unknown column type: bit  table name: tag column name: is_visible
Error occured in typeorm-model-generator.
typeorm-model-generator@0.2.22  node@v8.11.2
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
Error
    at Object.LogError (/usr/lib/node_modules/typeorm-model-generator/dist/src/Utils.js:10:21)
    at response.filter.forEach.resp (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:160:39)
    at Array.forEach (<anonymous>)
    at entities.forEach.ent (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:38:22)
    at Array.forEach (<anonymous>)
    at MariaDbDriver.<anonymous> (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:33:22)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/typeorm-model-generator/dist/src/drivers/MysqlDriver.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Table term_tag has no PK.
Error occured in typeorm-model-generator.
typeorm-model-generator@0.2.22  node@v8.11.2
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
Table word_mapping has no PK.
Error occured in typeorm-model-generator.
typeorm-model-generator@0.2.22  node@v8.11.2
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
[2:38:59 PM] Typeorm model classes created.
```

**Comment by Kononnable** [comment]
Bit type is not supported by typeorm. It shouldn't be much work to make it working there, but I guess nobody thought of that yet. When typeorm start supporting that type than #79 will be merged. http://typeorm.io/#/entities/column-types-for-mysql--mariadb

As for `Table ... has no PK` - these tables has no primary key defined. Typeorm(and many other ORMs) can't use entity which doesn't have primary key defined.

**Comment by P0oOOOo0YA** [comment]
@Kononnable Thanks for reaching out fast. As you have deep understanding of typeorm, What is the best workaround to deal with both `bit` type and tables with no PK?

**Comment by Kononnable** [comment]
As for `bit` - it probably should be easy to add it to `typeorm`. I think it is the best solution for it, but some folks use tinyint instead of bit.

As for no PK - I think you could try adding it to every column on generated entity model - if you won't use typoerm synchronization or migrations I think it should work well. If you want use  such features you probably would be required to change your schema and add PKs.

**Comment by Maia-Everett** [comment]
TypeORM now supports the `bit` type. The patch can be merged.
