### ISSUE TITLE
Relation between tables x and y didn't found entity column y.undefined.

### ISSUE THREAD

**Issue by Rafa0407** [Kononnable/typeorm-model-generator#133]
Someone can help me?  

The FK it's correct in both tables,  i run the script in mysql workbench and everything it's fine

**Comment by bertyhell** [comment]
I have the same issue.

the command:
```
typeorm-model-generator -h host -d db -p port -u user -x pw -e postgres -s app
```

output:
```
typeorm-model-generator@0.3.4
[10:11:06 AM] Starting creation of model classes.
Relation between tables collections and types didn't found entity model types.
Error occured in typeorm-model-generator.
typeorm-model-generator@0.3.4  node@v10.16.0
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
Error
    at Object.LogError (C:\Users\bert\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\Utils.js:10:21)
    at GetRelationsFromRelationTempInfo.relationsTemp.forEach.relationTmp (C:\Users\bert\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\drivers\AbstractDriver.js:149:27)
    at Array.forEach (<anonymous>)
    at PostgresDriver.GetRelationsFromRelationTempInfo (C:\Users\bert\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\drivers\AbstractDriver.js:141:23)
    at PostgresDriver.<anonymous> (C:\Users\bert\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\drivers\PostgresDriver.js:433:29)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\bert\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\drivers\PostgresDriver.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The issue is that these tables are referencing each other while they are in difference schemas.

for example:
The error occurs when table 1 has a foreign key that points to table 2
```
- db
      - schema 1
              - table 1
      - schema 2
              - table 2
```
