### ISSUE TITLE
Tables not found in selected database. Skipping creation of typeorm model.

### ISSUE THREAD

**Issue by lakamsani** [Kononnable/typeorm-model-generator#16]
Hi, A command like this (host, password etc changed for obvious reasons)
```bash
typeorm-model-generator -h host -p 15465 -d CustomDB -e postgres -o . -u myuser -x 1234  --ssl
```
Comes back with this. 

```bash
[12:45:56] Starting creation of model classes.
Tables not found in selected database. Skipping creation of typeorm model.
[12:45:56] Typeorm model classes created.
```

Any way to debug what is wrong? I can access the schema just fine from pgAdmin and node.js code via pg driver. 

```bash
typeorm-model-generator --version 
0.2.3
node --version
v8.9.0
macOS High Sierra 10.13.1
```

**Comment by lakamsani** [comment]
Was able to work around this by using a postgres db running on my mac with the tables in the public schema. 
```bash
# this worked
typeorm-model-generator -h localhost -d postgres -u vamsee -x vamsee -e postgres -o .
```

**Comment by lakamsani** [comment]
I 'm trying to run the app using `ts-node` using the reverse engineered entities. It is generating `@Column("datetime")` for timestamp fields  but Postgres does not have that type. So changed them all to `timestamp`. However when app starts up TypeORM seems to be synchronizing with the schema and fails as it attempts to re-create some indexes. for exmaple:

```bash
{ QueryFailedError: relation "uniqueuid" already exists
    at new QueryFailedError (/Users/vamsee/Development/typeorm-gen/src/error/QueryFailedError.ts:7:9)
    at Query.callback (/Users/vamsee/Development/typeorm-gen/src/driver/postgres/PostgresQueryRunner.ts:216:26)
    at Query.handleError (/Users/vamsee/Development/typeorm-gen/node_modules/pg/lib/query.js:143:17)
    at Connection.connectedErrorHandler (/Users/vamsee/Development/typeorm-gen/node_modules/pg/lib/client.js:132:26)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/Users/vamsee/Development/typeorm-gen/node_modules/pg/lib/connection.js:118:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
  message: 'relation "uniqueuid" already exists',
  name: 'QueryFailedError',
  length: 91,
  severity: 'ERROR',
  code: '42P07',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'index.c',
  line: '793',
  routine: 'index_create',
```

**Comment by lakamsani** [comment]
In `ormconfig.json` set `"synchronize": false,`

**Comment by Kononnable** [comment]
Everything should be working by now except casing styles. There is PR for that #23, so it will be added in couple of days and published as new version so it becomes available in npm.
