### ISSUE TITLE
Server requires encryption, set 'encrypt' config option to true.

### ISSUE THREAD

**Issue by reggiebeatz71** [Kononnable/typeorm-model-generator#181]
I tried generating my models from an azure database and it gives me this error.

`Server requires encryption, set 'encrypt' config option to true.
(node:6902) UnhandledPromiseRejectionWarning: ConnectionError: Server requires encryption, set 'encrypt' config option to true.
    at Connection.tedious.once.err (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/mssql/lib/tedious.js:239:17)
    at Object.onceWrapper (events.js:277:13)
    at Connection.emit (events.js:189:13)
    at Connection.processPreLoginResponse (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/tedious/lib/connection.js:1098:16)
    at Connection.message (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/tedious/lib/connection.js:1722:14)
    at Connection.dispatchEvent (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/tedious/lib/connection.js:1012:38)
    at MessageIO.<anonymous> (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/tedious/lib/connection.js:891:18)
    at MessageIO.emit (events.js:189:13)
    at Message.<anonymous> (/usr/local/lib/node_modules/typeorm-model-generator/node_modules/tedious/lib/message-io.js:60:15)
    at Message.emit (events.js:194:15)
(node:6902) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6902) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by paolobueno** [comment]
Ran into this briefly myself, solution is activating `--ssl`
