### ISSUE TITLE
"TypeError: The "config.options.port" property must be of type number." when using GetUtilParametersByInquirer()

### ISSUE THREAD

**Issue by tienleok** [Kononnable/typeorm-model-generator#209]
Fix:
In /src/index.ts line 246, change 
from: type: "input",
to: type: "number",

**Comment by ubilrodriguez** [comment]
TypeError: The "config.options.port" property must be of type number.
    at new Connection (C:\HHHHHHH\hbase\node_modules\mssql\node_modules\tedious\lib\connection.js:853:17)
    at C:\HHHHHHH\hbase\node_modules\mssql\lib\tedious\connection-pool.js:64:19
    at new Promise (<anonymous>)
    at ConnectionPool._poolCreate (C:\HHHHHHH\hbase\node_modules\mssql\lib\tedious\connection-pool.js:12:12)
    at ConnectionPool._connect (C:\HHHHHHH\hbase\node_modules\mssql\lib\base\connection-pool.js:364:10)
    at C:\HHHHHHH\hbase\node_modules\mssql\lib\base\connection-pool.js:336:19
    at new Promise (<anonymous>)
    at ConnectionPool.connect (C:\HHHHHHH\hbase\node_modules\mssql\lib\base\connection-pool.js:335:12)
    at Object.connect (C:\HHHHHHH\hbase\node_modules\mssql\lib\global-connection.js:59:27)
    at getIDENTIFICACION (C:\HHHHHHH\hbase\getiIDENTIFICACION.js:6:30)
[nodemon] clean exit - waiting for changes before restart
