### ISSUE TITLE
Generation fail when no PK is not found in 0.4.0

### ISSUE THREAD

**Issue by BigTony** [Kononnable/typeorm-model-generator#245]
Hi, 

generation in v0.4.0 with MSSQL driver fails instead of just giving warning stack trace:
```
typeorm-model-generator@0.4.0
[7:25:33 PM] Starting creation of model classes.
tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. node_modules/typeorm-model-generator/node_modules/mssql/lib/tedious/connection-pool.js:61:23
Table sys_db_update has no PK.
Error occurred in typeorm-model-generator.
typeorm-model-generator@0.4.0  node@v10.18.1
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
(node:16882) UnhandledPromiseRejectionWarning: SyntaxError: Argument expression expected. (115:23)
  113 | toDelete:boolean;
  114 | 
> 115 | @ManyToOne(()=>Import,import=>import.importHracs)
      |                       ^
  116 | @JoinColumn([{ name: "importid", referencedColumnName: "importId" },
  117 | ])
  118 | 
    at t (project/node_modules/typeorm-model-generator/node_modules/prettier/parser-typescript.js:1:285)
    at Object.parse (project/node_modules/typeorm-model-generator/node_modules/prettier/parser-typescript.js:14:180461)
    at Object.parse (project/node_modules/typeorm-model-generator/node_modules/prettier/index.js:9739:19)
    at coreFormat (project/node_modules/typeorm-model-generator/node_modules/prettier/index.js:13252:23)
    at format (project/node_modules/typeorm-model-generator/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (project/node_modules/typeorm-model-generator/node_modules/prettier/index.js:13526:12)
    at project/node_modules/typeorm-model-generator/node_modules/prettier/index.js:44207:15
    at Object.format (project/node_modules/typeorm-model-generator/node_modules/prettier/index.js:44226:12)
    at databaseModel.forEach.element (project/node_modules/typeorm-model-generator/dist/src/ModelGeneration.js:56:36)
    at Array.forEach (<anonymous>)
(node:16882) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16882) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

but it runs fine on v0.3.5 just prints out: 
```
typeorm-model-generator@0.3.5
[7:26:54 PM] Starting creation of model classes.
Table sys_db_update has no PK.
Error occured in typeorm-model-generator.
typeorm-model-generator@0.3.5  node@v10.18.1
```
and generate all entities.
This probably re-introduce #54

**Comment by BigTony** [comment]
Ahh I've just realized that this is probably caused by table that is named "import" in db schema ... so dumb name
