### ISSUE TITLE
while generating  from SQL Server database syntax error occurs and exited.

### ISSUE THREAD

**Issue by amirofy2002** [Kononnable/typeorm-model-generator#247]
(node:9492) UnhandledPromiseRejectionWarning: SyntaxError: Identifier expected. (515:43)
  513 | stockUseds:StockUsed[];
  514 | 
> 515 | @OneToOne(()=>Students,students=>students.)
      |                                           ^
  516 | 
  517 | 
  518 | students:Students;

**Comment by amirofy2002** [comment]
(node:9492) UnhandledPromiseRejectionWarning: SyntaxError: Identifier expected. (515:43)
  513 | stockUseds:StockUsed[];
  514 | 
> 515 | @OneToOne(()=>Students,students=>students.)
      |                                           ^
  516 | 
  517 | 
  518 | students:Students;
    at t (C:\Users\admin\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\prettier\parser-typescript.js:1:285)
    at Object.parse (C:\Users\admin\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\prettier\parser-typescript.js:14:180461)
    at Object.parse (C:\Users\admin\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\prettier\index.js:9739:19)
    at coreFormat (C:\Users\admin\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\prettier\index.js:13252:23)
    at format (C:\Users\admin\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\prettier\index.js:13510:73)
    at formatWithCursor (C:\Users\admin\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\prettier\index.js:13526:12)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\prettier\index.js:44207:15
    at Object.format (C:\Users\admin\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\prettier\index.js:44226:12)
    at databaseModel.forEach.element (C:\Users\admin\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\ModelGeneration.js:56:36)
    at Array.forEach (<anonymous>)

**Comment by Kononnable** [comment]
Could you please provide DDL statements for schema which gives such error(reproduction example)? There is no way to tell what's wrong just by that error message - all we know is that generated code isn't a valid typescript code.

**Comment by Kononnable** [comment]
Closing as no response from the author.
