### ISSUE TITLE
while generating from PostgreSQL database syntax error occurs and exited.

### ISSUE THREAD

**Issue by datamaker** [Kononnable/typeorm-model-generator#248]
Doesn't the default support for jsonb types?

[2:08:54 AM] Starting creation of model classes.
(node:58765) DeprecationWarning: Implicit disabling of certificate verification is deprecated and will be removed in pg 8. Specify `rejectUnauthorized: true` to require a valid CA or `rejectUnauthorized: false` to explicitly opt out of MITM protection.
(node:58765) UnhandledPromiseRejectionWarning: SyntaxError: ',' expected. (15:66)
  13 | id:string;
  14 | 
> 15 | **@Column("jsonb",{ name:"colums",nullable:true,default: () => "'{"type": null, "values": true}'", })**
     |                                                                  ^
  16 | colums:object | null;
  17 | 
  18 | @ManyToOne(()=>Groups,groups=>groups.inventoryLayouts,{ onDelete:"CASCADE",onUpdate:"CASCADE" })
    at t (/Users/dm/.nvm/versions/node/v10.16.3/lib/node_modules/typeorm-model-generator/node_modules/prettier/parser-typescript.js:1:285)
    at Object.parse (/Users/dm/.nvm/versions/node/v10.16.3/lib/node_modules/typeorm-model-generator/node_modules/prettier/parser-typescript.js:14:180461)
    at Object.parse (/Users/dm/.nvm/versions/node/v10.16.3/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:9739:19)
    at coreFormat (/Users/dm/.nvm/versions/node/v10.16.3/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:13252:23)
    at format (/Users/dm/.nvm/versions/node/v10.16.3/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:13510:73)
    at formatWithCursor (/Users/dm/.nvm/versions/node/v10.16.3/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:13526:12)
    at /Users/dm/.nvm/versions/node/v10.16.3/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:44207:15
    at Object.format (/Users/dm/.nvm/versions/node/v10.16.3/lib/node_modules/typeorm-model-generator/node_modules/prettier/index.js:44226:12)
    at databaseModel.forEach.element (/Users/dm/.nvm/versions/node/v10.16.3/lib/node_modules/typeorm-model-generator/dist/src/ModelGeneration.js:56:36)
    at Array.forEach (<anonymous>)
(node:58765) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:58765) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Kononnable** [comment]
Looks like default value isn't properly escaped.

**Comment by Kononnable** [comment]
Released in `typeorm-model-generator@0.4.2`.
