### ISSUE TITLE
Client does not support authentication protocol requested by server while generating

### ISSUE THREAD

**Issue by Flusinerd** [Kononnable/typeorm-model-generator#251]
Hello,
I cannot connect use this tool on my MySQL Server that ist > V8.x
I am get the following error:
```
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
(node:18192) UnhandledPromiseRejectionWarning: Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
    at Handshake.Sequence._packetToError (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at TLSSocket.ondata (_stream_readable.js:667:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    --------------------
    at Protocol._enqueue (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\mysql\lib\Connection.js:116:18)
    at ConnectToServer.Promise (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\drivers\MysqlDriver.js:345:29)
    at new Promise (<anonymous>)
    at MysqlDriver.ConnectToServer (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\drivers\MysqlDriver.js:343:25)
    at MysqlDriver.GetDataFromServer (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\drivers\AbstractDriver.js:116:20)
    at dataCollectionPhase (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\Engine.js:43:19)
    at Object.createModelFromDatabase (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\Engine.js:33:25)
    at CliLogic (C:\Users\Jan\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\index.js:27:20)
(node:18192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Kononnable** [comment]
I think this might be what you're looking for:
https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server/53382070

**Comment by Joniras** [comment]
Actuall using a less secure method to authenticate is not a good solution.   
Using the mysql2 package to connect or keeping the issue open until mysql 3.x comes out seems more appropriate to me.
