### ISSUE TITLE
Can I set entity database name in console options?

### ISSUE THREAD

**Issue by capinemo** [Kononnable/typeorm-model-generator#265]
Hello! Thanx a lot for your module!

Now, generation entities sets a scheme in a Entity decorator. Can I specify any way a entities database?
I need substring as `@Entity({ database: 'notifier' })` in entities. If this is not possible, how do you see me implementing it

**Comment by Kononnable** [comment]
I think it will generate database in entity option by default if there is more then one database specified in the options. If you're targeting one database simply adding comma at the end of db name should help(`-d dbname,`). Not very obvious way to do this, but it worked before.

**Comment by capinemo** [comment]
Unfortunately no.
`
$ typeorm-model-generator --host pg.stage.base.com --port 5432 --database baseName, --user name --pass pass --output ./old/base --engine postgres --noConfig --case-file camel  --case-entity camel --case-property camel 
`

`
typeorm-model-generator@0.4.2
[23:22:15] Starting creation of model classes.
Error connecting to Postgres Server.
Error occurred in typeorm-model-generator.
typeorm-model-generator@0.4.2  node@v13.12.0
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
database "baseName," does not exist
(node:7155) UnhandledPromiseRejectionWarning: error: database "baseName," does not exist
    at Connection.parseE (/home/nemo/work/repo/apps/develop-typeorm-models/node_modules/pg/lib/connection.js:600:48)
    at Connection.parseMessage (/home/nemo/work/repo/apps/develop-typeorm-models/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/home/nemo/work/repo/apps/develop-typeorm-models/node_modules/pg/lib/connection.js:115:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
`

**Comment by Kononnable** [comment]
Sorry for the delay I didn't have much time for OSS lately.
Did you solve the problem or do you still need help with that?

**Comment by capinemo** [comment]
Hi!
Thanks, solved, not actual. Decided to use schemes
