### ISSUE TITLE
[MSSQL]  UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of null

### ISSUE THREAD

**Issue by hunglee** [Kononnable/typeorm-model-generator#299]
I use the default CMD to generate entire database model, it's throw this error after running. I'm using the newest version anh nodejs v12. Thanks
> (node:14840) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startsWith' of null
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\ModelCustomization.js:67:64
    at Array.filter (<anonymous>)
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\ModelCustomization.js:67:41
    at Array.forEach (<anonymous>)
    at removeIndicesGeneratedByTypeorm (C:\Users\xxx\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\ModelCustomization.js:66:13)
    at Object.modelCustomizationPhase [as default] (C:\Users\xxx\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\ModelCustomization.js:55:18)
    at Object.createModelFromDatabase (C:\Users\xxx\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\Engine.js:38:43)
    at async CliLogic (C:\Users\xxx\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\index.js:27:5)
(node:14840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Kononnable** [comment]
Looks like there is an index with null name. Weird.
Which db engine(and version) are you using?
