### ISSUE TITLE
Error connecting to MSSQL Server.

### ISSUE THREAD

**Issue by davidd22** [Kononnable/typeorm-model-generator#325]
hi 

iam trying to connect to an SQL server but I am guessing I am doing something wrong ...

full error msg 

```
Error connecting to MSSQL Server.
Error occurred in typeorm-model-generator.
typeorm-model-generator@0.4.4  node@v14.15.2
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
Failed to connect to localhost:1433 - Could not connect (sequence)
(node:26492) UnhandledPromiseRejectionWarning: ConnectionError: Failed to connect to localhost:1433 - Could not connect (sequence)
    at Connection.<anonymous> (C:\Users\admin\source\repos\user-management-api\node_modules\mssql\lib\tedious\connection-pool.js:68:17)
    at Object.onceWrapper (events.js:422:26)
    at Connection.emit (events.js:315:20)
    at Connection.socketError (C:\Users\admin\source\repos\user-management-api\node_modules\tedious\lib\connection.js:1290:12)
    at C:\Users\admin\source\repos\user-management-api\node_modules\tedious\lib\connection.js:1116:21
    at SequentialConnectionStrategy.connect (C:\Users\admin\source\repos\user-management-api\node_modules\tedious\lib\connector.js:87:14)
    at Socket.onError (C:\Users\admin\source\repos\user-management-api\node_modules\tedious\lib\connector.js:100:12)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

this is how I am trying to connect 

npx typeorm-model-generator -h localhost -p 1433 -d UsersDb  -u username-x password -e mssql -o src/data-layer/entity

any ideas ?

thanks

**Comment by achauhan-bithub** [comment]
typeorm-model-generator -h .\sqlexpress14 -d mydb -u sa -x !password -e mssql -o
typeorm-model-generator@0.4.4
Starting creation of model classes.
tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. node_modules\typeorm-model-generator\node_modules\mssql\lib\tedious\connection-pool.js:61:23
Error connecting to MSSQL Server.
Error occurred in typeorm-model-generator.
typeorm-model-generator@0.4.4  node@v14.15.2
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
Failed to connect to .\sqlexpress14 in 15000ms
(node:12240) UnhandledPromiseRejectionWarning: ConnectionError: Failed to connect to .\sqlexpress14 in 15000ms
    at Connection.<anonymous> (C:\Users\akhil.chauhan\AppData\Roaming\npm\node_modules\typeorm-model-generator\node_modules\mssql\lib\tedious\connection-pool.js:68:17)
    at Object.onceWrapper (events.js:422:26)
    at Connection.emit (events.js:315:20)
    at Connection.connectTimeout (%userprofile%\npm\node_modules\typeorm-model-generator\node_modules\tedious\lib\connection.js:1195:10)
    at Timeout._onTimeout (%userprofile%\npm\node_modules\typeorm-model-generator\node_modules\tedious\lib\connection.js:1157:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:12240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

**Comment by Kononnable** [comment]
@davidd22 take a look at https://github.com/typeorm/typeorm/issues/2133 probably related to sql server not being configured properly for tcp connection
@achauhan-bithub `-h` parameter looks wrong - it soupposed to be hostname/ip address, for instance name there is `-i`

**Comment by achauhan-bithub** [comment]
@davidd22 , able to connect now after setting up correctly from  [https://github.com/typeorm/typeorm/issues/2133] 
However, not able find tables 
 Starting creation of model classes.
tedious deprecated The default value for `config.options.enableArithAbort` will change from `false` to `true` in the next major version of `tedious`. Set the value to `true` or `false` explicitly to silence this message. node_modules\typeorm-model-generator\node_modules\mssql\lib\tedious\connection-pool.js:61:23
**Tables not found in selected database. Skipping creation of typeorm model.**
Error occurred in typeorm-model-generator.
typeorm-model-generator@0.4.4  node@v14.15.2
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
[10:47:14 am] Typeorm model classes created.
