### ISSUE TITLE
Unknown column type:USER-DEFINED

### ISSUE THREAD

**Issue by antoine-pous** [Kononnable/typeorm-model-generator#33]
Hi !

When i'm trying to generate the models from PgSQL i have this error:

```
git@Loki:~/io/node-api$ ./node_modules/.bin/typeorm-model-generator -h <IP> -d <DB> -u <USER> -x <PASS> -p <PORT> -e postgres -o src/models/ -s <SCHEMA> --noconfig --ssl
[11:13:59] Starting creation of model classes.
Unknown column type:USER-DEFINED
Fatal error occured.
typeorm-model-generator@0.2.6  node@v8.6.0
Fatal error occured in typeorm-model-generator.
If this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
Error
    at Object.LogFatalError (/home/git/io/node-api/node_modules/typeorm-model-generator/dist/src/Utils.js:12:21)
    at response.filter.forEach (/home/git/io/node-api/node_modules/typeorm-model-generator/dist/src/drivers/PostgresDriver.js:214:39)
    at Array.forEach (<anonymous>)
    at entities.forEach (/home/git/io/node-api/node_modules/typeorm-model-generator/dist/src/drivers/PostgresDriver.js:58:20)
    at Array.forEach (<anonymous>)
    at PostgresDriver.<anonymous> (/home/git/io/node-api/node_modules/typeorm-model-generator/dist/src/drivers/PostgresDriver.js:55:22)
    at Generator.next (<anonymous>)
    at fulfilled (/home/git/io/node-api/node_modules/typeorm-model-generator/dist/src/drivers/PostgresDriver.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 1: node::Abort() [node]
 2: 0x1356e29 [node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 4: 0xc13f5a [node]
 5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 6: 0x2328b1c046fd
Abandon (core dumped)
```

**Comment by Kononnable** [comment]
Could you provide database schema? There is probably column with user defined type, and it doesn't know how to handle it.
I'm not sure if it is really user defined type or if some types supported by orm are marked as user defined.

**Comment by Kononnable** [comment]
Closing as no answer from reporter.

**Comment by grmartin** [comment]
@Kononnable I actually just ran in to this, for me it is the case of a `USER-DEFINED` type. Is there any way to support this?

**Comment by Kononnable** [comment]
I'll put them on my todo list.
Could you give an example of table with composite type(DDL statements) and how it should be mapped to typeorm?

**Comment by JamesYFC** [comment]
i'm running into the "Unknown USER-DEFINED column type" error. In my case I have an enum. Is it possible to translate this column into the typescript entity like so:

column of user defined type Enum('a', 'b', 'c') -> property of type 'a' | 'b' | 'c'
