### ISSUE TITLE
Unkown column 'FULLTEXT' in 'field list'

### ISSUE THREAD

**Issue by lennyparisineu** [Kononnable/typeorm-model-generator#331]
I'm trying to generate typeorm models using this generator, but when I try running

`npx typeorm-model-generator -h $DB_HOST -d $DB_NAME -u $DB_USER -x $DB_PASSWD -p $DB_PORT -e $DB_DIALECT`

I get the following error:

```sh
Error: Unknown column 'FULLTEXT' in 'field list'
    at Packet.asError (/home/lenny/.npm/_npx/37c2d66b7ffa4fe9/node_modules/mysql2/lib/packets/packet.js:712:17)
    at Query.execute (/home/lenny/.npm/_npx/37c2d66b7ffa4fe9/node_modules/mysql2/lib/commands/command.js:28:26)
    at Connection.handlePacket (/home/lenny/.npm/_npx/37c2d66b7ffa4fe9/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/home/lenny/.npm/_npx/37c2d66b7ffa4fe9/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/home/lenny/.npm/_npx/37c2d66b7ffa4fe9/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/lenny/.npm/_npx/37c2d66b7ffa4fe9/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10) {
      code: 'ER_BAD_FIELD_ERROR',
      errno: 1054,
      sqlState: '42S22',
      sqlMessage: "Unknown column 'FULLTEXT' in 'field list'"
    }
```

I'm not sure if this is a bug or an actual issue but I was unable to find anything online so any help would be greatly appreciated.

**Comment by Kononnable** [comment]
Which version of db engine are you using? I mean name(mysql/mariadb) and version. 
Unfortunately error isn't very helpful, my only guess right now is incompatible versions, but I don't see anything in particular which may cause such behavior.
