### ISSUE TITLE
0.2.8 missing dist?

### ISSUE THREAD

**Issue by ravihugo** [Kononnable/typeorm-model-generator#42]
Seems like it's related to the bash/node script where it runs: require('../dist/src/index'); Possibly because the build wasn't run before the npm push?
The previous version 0.2.7 doesn't seem affected.

module.js:559
    throw err;
    ^

Error: Cannot find module '../dist/src/index'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/hugo/hugo/hugo-rest-ts/node_modules/typeorm-model-generator/bin/typeorm-model-generator:6:1)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)

**Comment by Kononnable** [comment]
Looks like you're right. Published version with code this time. 
Thanks.
