### ISSUE TITLE
Command fails if password is an integer

### ISSUE THREAD

**Issue by Slessi** [Kononnable/typeorm-model-generator#43]
Hi,

When the supplied password only contains numerical characters, I run into the following

```bash
typeorm-model-generator -e mysql -h localhost -d mydb -u root -x 123
```

```js
[16:36:05] Starting creation of model classes.
/.../node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: "value" argument must not be a number
    at Function.Buffer.from (buffer.js:186:11)
    at Object.Auth.token (/.../node_modules/mysql/lib/protocol/Auth.js:29:29)
    at Handshake._sendCredentials (/.../node_modules/mysql/lib/protocol/sequences/Handshake.js:105:14)
    at Handshake.HandshakeInitializationPacket (/.../node_modules/mysql/lib/protocol/sequences/Handshake.js:87:10)
    at Protocol._parsePacket (/.../node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/.../node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/.../node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/.../node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
```

Adding any non-numerical characters to the password resolves the issue.
I tried the following but to no avail:

```bash
-x123
-x=123
-x="123"
-x='123'
```

**Comment by Slessi** [comment]
https://github.com/Kononnable/typeorm-model-generator/blob/d3ca1f9a7a0d56a799405c60a84c847fb1034234/src/index.ts#L119

`.toString()` here fixes it

**Comment by Kononnable** [comment]
Thanks for your report.
Fixed in `typeorm@0.2.10`

**Comment by Slessi** [comment]
@Kononnable Thanks for the quick update, however:

```
$ typeorm-model-generator -e mysql -h localhost -d database -p 3366 -u user -x 123 -o ./src/entity --noConfig --cf pascal --ce pascal --cp camel && tslint --fix ./src/entity/**/*.ts --force -c
/.../node_modules/typeorm-model-generator/dist/src/index.js:116
    schemaName: argv.s.toString() || standardSchema,
                       ^

TypeError: Cannot read property 'toString' of undefined
    at Object.<anonymous> (/.../node_modules/typeorm-model-generator/dist/src/index.js:116:24)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/.../node_modules/typeorm-model-generator/bin/typeorm-model-generator:6:1)
    at Module._compile (module.js:643:30)
```

**Comment by ruslanraupoff** [comment]
You can use  _argv.s.toString()_ change toString(argv.s) in index.js

**Comment by Kononnable** [comment]
Fixed it again. I hope this time without introducing new bugs.

@ruslanraupoff toString() on undefined will return `"[object Undefined]"`, so I just check if value is falsy.
