### ISSUE TITLE
RangeError: Index out of range

### ISSUE THREAD

**Issue by cesarve77** [Kononnable/typeorm-model-generator#75]
Trying to generate my entities I get the follow error:

`
RangeError: Index out of range
    at checkOffset (buffer.js:977:11)
    at Buffer.readUInt8 (buffer.js:1015:5)
    at Packet.isLast (/usr/local/share/.config/yarn/global/node_modules/tedious/lib/packet.js:116:29)
    at ReadablePacketStream.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/tedious/lib/message-io.js:101:18)
    at emitOne (events.js:116:13)
    at ReadablePacketStream.emit (events.js:211:7)
    at addChunk (/usr/local/share/.config/yarn/global/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/usr/local/share/.config/yarn/global/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at ReadablePacketStream.Readable.push (/usr/local/share/.config/yarn/global/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at ReadablePacketStream.Transform.push (/usr/local/share/.config/yarn/global/node_modules/readable-stream/lib/_stream_transform.js:148:32)
`
Im using mysql 8

**Comment by cesarve77** [comment]
My bad, I was using mssql option in a mysql server
