### ISSUE TITLE
any idea about `UnhandledPromiseRejectionWarning: RequestError: Timeout: Request failed to complete in 15000ms`

### ISSUE THREAD

**Issue by HaveF** [Kononnable/typeorm-model-generator#80]
Hi, thanks for your repo.

I tried like this, 
`npx typeorm-model-generator@no-engines -h xxxxx -p 1433 -u username -x password -d dbname -e mssql -o ./src/entities`
but get error like this:

```
npx: installed 1 in 2.034s
The "path" argument must be of type string
npx: installed 196 in 19.965s
C:\Users\dell\AppData\Roaming\npm-cache\_npx\1688\node_modules\typeorm-model-generator\bin\typeorm-model-generator
[09:42:41] Starting creation of model classes.
tedious deprecated The `IntN` data type is internal and will be removed. ..\..\Users\dell\AppData\Roaming\npm-cache\_npx\1688\node_modules\typeorm-model-generator\node_modules\mssql\lib\tedious.js:63:20
(node:1688) UnhandledPromiseRejectionWarning: RequestError: Timeout: Request failed to complete in 15000ms
    at Request.tds.Request.err [as userCallback] (C:\Users\dell\AppData\Roaming\npm-cache\_npx\1688\node_modules\typeorm-model-generator\node_modules\mssql\lib\tedious.js:578:19)
    at Request._this.callback (C:\Users\dell\AppData\Roaming\npm-cache\_npx\1688\node_modules\typeorm-model-generator\node_modules\tedious\lib\request.js:60:27)
    at Connection.message (C:\Users\dell\AppData\Roaming\npm-cache\_npx\1688\node_modules\typeorm-model-generator\node_modules\tedious\lib\connection.js:1936:24)
    at Connection.dispatchEvent (C:\Users\dell\AppData\Roaming\npm-cache\_npx\1688\node_modules\typeorm-model-generator\node_modules\tedious\lib\connection.js:992:38)
    at MessageIO.<anonymous> (C:\Users\dell\AppData\Roaming\npm-cache\_npx\1688\node_modules\typeorm-model-generator\node_modules\tedious\lib\connection.js:886:18)
    at MessageIO.emit (events.js:180:13)
    at ReadablePacketStream.<anonymous> (C:\Users\dell\AppData\Roaming\npm-cache\_npx\1688\node_modules\typeorm-model-generator\node_modules\tedious\lib\message-io.js:102:16)
    at ReadablePacketStream.emit (events.js:180:13)
    at addChunk (C:\Users\dell\AppData\Roaming\npm-cache\_npx\1688\node_modules\typeorm-model-generator\node_modules\readable-stream\lib\_stream_readable.js:291:12)
    at readableAddChunk (C:\Users\dell\AppData\Roaming\npm-cache\_npx\1688\node_modules\typeorm-model-generator\node_modules\readable-stream\lib\_stream_readable.js:278:11)
(node:1688) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1688) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

what can I do next? Thanks!

**Comment by Kononnable** [comment]
It looks like request took to much time to complete. Not sure why, 15 seconds is a long period.
Could there be a schema lock while generating models(someone altering tables, probably in a transaction)?

You can try running queries by hand - to see if it is something database related(locks) or driver related.
https://github.com/Kononnable/typeorm-model-generator/blob/master/src/drivers/MssqlDriver.ts - search for request.query and replace `in (${schema})` with `in ('dbo')`

**Comment by HaveF** [comment]
After run queries by hand(it's ok), I retry the command, it works.

Maybe the db is in high load that day.

Thanks for ur repo again!

Btw, `@no-engines` would be better in doc.

**Comment by Crocetti** [comment]
How to increase the timeout, my database contains many tables and the average query time is 21000 ms.
