### ISSUE TITLE
error generating citext columns in Postgres database

### ISSUE THREAD

**Issue by shaunc** [Kononnable/typeorm-model-generator#81]
With table column of type citext, I get:
```
Error occured in typeorm-model-generator.
typeorm-model-generator@0.2.16-no-engines.2  node@v10.4.0
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
Error
    at Object.LogError (/Users/shauncutts/.config/yarn/global/node_modules/typeorm-model-generator/dist/src/Utils.js:11:21)
    at response.filter.forEach.resp (/Users/shauncutts/.config/yarn/global/node_modules/typeorm-model-generator/dist/src/drivers/PostgresDriver.js:252:39)
    at Array.forEach (<anonymous>)
    at entities.forEach.ent (/Users/shauncutts/.config/yarn/global/node_modules/typeorm-model-generator/dist/src/drivers/PostgresDriver.js:58:22)
    at Array.forEach (<anonymous>)
    at PostgresDriver.<anonymous> (/Users/shauncutts/.config/yarn/global/node_modules/typeorm-model-generator/dist/src/drivers/PostgresDriver.js:53:22)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/shauncutts/.config/yarn/global/node_modules/typeorm-model-generator/dist/src/drivers/PostgresDriver.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Unknown column type: USER-DEFINED  table name: fund_fundchange column name: newName```

**Comment by Kononnable** [comment]
Implemented in `typeorm-model-generator@0.2.20`
