### ISSUE TITLE
Support Geometry type

### ISSUE THREAD

**Issue by erikvullings** [Kononnable/typeorm-model-generator#85]
Cannot create models as each of my PostgreSQL tables have a column, geom, which contains a (PostGIS) geometry type. Is there a simple option to exclude these columns, or, even better, to support them? 

```console
typeorm-model-generator@0.2.18
[11:47:30] Starting creation of model classes.
Unknown column type: USER-DEFINED  table name: gem_2017 column name: geom
Error occured in typeorm-model-generator.
typeorm-model-generator@0.2.18  node@v8.11.2
If you think this is a bug please open an issue including this log on https://github.com/Kononnable/typeorm-model-generator/issues
Error
    at Object.LogError (C:\Users\erikv\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\Utils.js:10:21)
    at response.filter.forEach.resp (C:\Users\erikv\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\drivers\PostgresDriver.js:238:39)
    at Array.forEach (<anonymous>)
    at entities.forEach.ent (C:\Users\erikv\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\drivers\PostgresDriver.js:45:22)
    at Array.forEach (<anonymous>)
    at PostgresDriver.<anonymous> (C:\Users\erikv\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\drivers\PostgresDriver.js:40:22)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\erikv\AppData\Roaming\npm\node_modules\typeorm-model-generator\dist\src\drivers\PostgresDriver.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by Kononnable** [comment]
It looks like there are problems with geometry columns in typeorm. typeorm/typeorm#2610
Geometry columns should work with generator after being fixed in typeorm repo.
